import { RoomType, InteriorStyle } from '@/types';

export const ROOM_TYPES: RoomType[] = [
  { id: 'living-room', name: 'Living Room', icon: '🛋️', category: 'residential' },
  { id: 'bedroom', name: 'Bedroom', icon: '🛏️', category: 'residential' },
  { id: 'kitchen', name: 'Kitchen', icon: '🍳', category: 'residential' },
  { id: 'kitchen-living', name: 'Kitchen Living Combo', icon: '🏠', category: 'residential' },
  { id: 'bathroom', name: 'Bathroom', icon: '🚿', category: 'residential' },
  { id: 'dining-room', name: 'Dining Room', icon: '🍽️', category: 'residential' },
  { id: 'kids-room', name: 'Kids Room', icon: '🧸', category: 'residential' },
  { id: 'study-room', name: 'Study Room', icon: '📚', category: 'residential' },
  { id: 'home-office', name: 'Home Office', icon: '💻', category: 'residential' },
  { id: 'gaming-room', name: 'Gaming Room', icon: '🎮', category: 'residential' },
  { id: 'walk-in-closet', name: 'Walk-in Closet', icon: '👗', category: 'residential' },
  { id: 'hallway', name: 'Hallway', icon: '🚪', category: 'residential' },
  { id: 'attic', name: 'Attic', icon: '🏚️', category: 'residential' },
  { id: 'gym', name: 'Gym', icon: '🏋️', category: 'residential' },
  { id: 'garage', name: 'Garage', icon: '🚗', category: 'residential' },
  { id: 'outdoor-patio', name: 'Outdoor Patio', icon: '🌿', category: 'outdoor' },
  { id: 'outdoor-garden', name: 'Outdoor Garden', icon: '🌳', category: 'outdoor' },
  { id: 'outdoor-pool', name: 'Pool Area', icon: '🏊', category: 'outdoor' },
  { id: 'house-exterior', name: 'House Exterior', icon: '🏡', category: 'outdoor' },
  { id: 'office', name: 'Office', icon: '🏢', category: 'commercial' },
  { id: 'meeting-room', name: 'Meeting Room', icon: '🤝', category: 'commercial' },
  { id: 'conference-hall', name: 'Conference Hall', icon: '🎤', category: 'commercial' },
  { id: 'restaurant', name: 'Restaurant', icon: '🍝', category: 'commercial' },
  { id: 'coffee-shop', name: 'Coffee Shop', icon: '☕', category: 'commercial' },
  { id: 'store', name: 'Retail Store', icon: '🛍️', category: 'commercial' },
  { id: 'hotel-room', name: 'Hotel Room', icon: '🏨', category: 'commercial' },
  { id: 'hotel-lobby', name: 'Hotel Lobby', icon: '🛎️', category: 'commercial' },
  { id: 'coworking', name: 'Coworking Space', icon: '👥', category: 'commercial' },
  { id: 'airport-lounge', name: 'Airport Lounge', icon: '✈️', category: 'commercial' },
  { id: 'library', name: 'Library', icon: '📖', category: 'commercial' },
  { id: 'cinema', name: 'Cinema', icon: '🎬', category: 'special' },
  { id: 'gallery', name: 'Gallery', icon: '🖼️', category: 'special' },
  { id: 'museum', name: 'Museum', icon: '🏛️', category: 'special' },
  { id: 'spa', name: 'Spa', icon: '🧖', category: 'special' },
  { id: 'podcast-studio', name: 'Podcast Studio', icon: '🎙️', category: 'special' },
];

export const INTERIOR_STYLES: InteriorStyle[] = [
  { id: 'modern', name: 'Modern', emoji: '🏠', description: 'Clean lines, neutral colors, functional furniture', category: 'modern', promptModifier: 'modern interior design, clean lines, minimalist furniture, neutral palette' },
  { id: 'contemporary', name: 'Contemporary', emoji: '✨', description: 'Current trends, bold accents, open spaces', category: 'modern', promptModifier: 'contemporary interior, current design trends, bold accents, open floor plan' },
  { id: 'minimalist', name: 'Minimalist', emoji: '🪟', description: 'Less is more, essential only, serene spaces', category: 'modern', promptModifier: 'minimalist interior, less is more, essential furniture only, serene and uncluttered' },
  { id: 'scandinavian', name: 'Scandinavian', emoji: '🌲', description: 'Light wood, hygge, functional beauty', category: 'modern', promptModifier: 'scandinavian interior design, light wood, hygge atmosphere, functional beauty, white walls' },
  { id: 'luxury', name: 'Luxury', emoji: '💎', description: 'Rich materials, elegant finishes, opulent', category: 'modern', promptModifier: 'luxury interior design, rich materials, gold accents, marble, velvet, opulent finishes' },
  { id: 'industrial', name: 'Industrial', emoji: '🏗️', description: 'Exposed brick, metal, raw materials', category: 'modern', promptModifier: 'industrial interior design, exposed brick, metal beams, raw concrete, Edison bulbs' },
  { id: 'midcentury', name: 'Mid-Century Modern', emoji: '🕰️', description: '50s-60s inspired, organic shapes, retro', category: 'modern', promptModifier: 'mid-century modern interior, 1950s 1960s inspired, organic shapes, teak wood, retro furniture' },
  { id: 'biophilic', name: 'Biophilic', emoji: '🌿', description: 'Nature-integrated, living walls, organic', category: 'modern', promptModifier: 'biophilic interior design, living walls, natural materials, indoor plants, nature integration' },
  { id: 'boho', name: 'Bohemian', emoji: '🧣', description: 'Eclectic layers, rich textures, worldly', category: 'classic', promptModifier: 'bohemian interior, eclectic layers, rich textures, macrame, colorful textiles, worldly decor' },
  { id: 'boho-chic', name: 'Boho-Chic', emoji: '📿', description: 'Bohemian meets elegance', category: 'classic', promptModifier: 'boho-chic interior, bohemian meets elegance, layered textures, earthy tones, artistic elements' },
  { id: 'farmhouse', name: 'Farmhouse', emoji: '🚜', description: 'Rustic charm, shiplap, vintage finds', category: 'classic', promptModifier: 'farmhouse interior design, rustic charm, shiplap walls, vintage finds, barn doors' },
  { id: 'french', name: 'French', emoji: '🥐', description: 'Parisian elegance, ornate details', category: 'classic', promptModifier: 'french interior design, parisian elegance, ornate moldings, antique furniture, soft colors' },
  { id: 'mediterranean', name: 'Mediterranean', emoji: '🌊', description: 'Warm earth tones, terracotta, arched', category: 'classic', promptModifier: 'mediterranean interior, warm earth tones, terracotta tiles, arched doorways, wrought iron' },
  { id: 'art-deco', name: 'Art Deco', emoji: '🎨', description: 'Geometric patterns, bold colors, glamour', category: 'classic', promptModifier: 'art deco interior design, geometric patterns, bold colors, gold accents, 1920s glamour' },
  { id: 'rustic', name: 'Rustic', emoji: '🍂', description: 'Natural wood, stone, country warmth', category: 'classic', promptModifier: 'rustic interior design, natural wood, stone accents, country warmth, exposed beams' },
  { id: 'coastal', name: 'Coastal', emoji: '🏖️', description: 'Ocean inspired, light blues, sandy neutrals', category: 'classic', promptModifier: 'coastal interior design, ocean inspired, light blues, sandy neutrals, nautical elements' },
  { id: 'zen', name: 'Zen', emoji: '🧘', description: 'Japanese minimalism, balance, tranquility', category: 'classic', promptModifier: 'zen interior design, japanese minimalism, balance, tranquility, natural materials, wabi-sabi' },
  { id: 'neoclassic', name: 'Neoclassic', emoji: '🏛️', description: 'Classical revival, symmetry, grandeur', category: 'classic', promptModifier: 'neoclassical interior design, classical revival, symmetry, columns, grandeur' },
  { id: 'japanese', name: 'Japanese', emoji: '🎌', description: 'Wabi-sabi, tatami, sliding doors', category: 'classic', promptModifier: 'japanese interior design, wabi-sabi, tatami mats, sliding shoji doors, low furniture' },
  { id: 'gaming', name: 'Gaming Room', emoji: '🎮', description: 'RGB lighting, battlestation, immersive', category: 'themed', promptModifier: 'gaming room setup, RGB lighting, multiple monitors, gaming chair, immersive atmosphere' },
  { id: 'futuristic', name: 'Futuristic', emoji: '🚀', description: 'Sci-fi inspired, LED, sleek surfaces', category: 'themed', promptModifier: 'futuristic interior design, sci-fi inspired, LED lighting, holographic elements, sleek surfaces' },
  { id: 'cyberpunk', name: 'Cyberpunk', emoji: '🌆', description: 'Neon lights, high-tech low-life', category: 'themed', promptModifier: 'cyberpunk interior, neon lights, high-tech low-life aesthetic, dark atmosphere, LED strips' },
  { id: 'retro-futuristic', name: 'Retro Futuristic', emoji: '🛸', description: '60s vision of the future', category: 'themed', promptModifier: 'retro futuristic interior, 1960s vision of the future, space age furniture, curved shapes' },
  { id: 'vintage', name: 'Vintage', emoji: '📻', description: 'Nostalgic charm, antique pieces', category: 'themed', promptModifier: 'vintage interior design, nostalgic charm, antique pieces, retro wallpaper, classic patterns' },
  { id: 'eclectic', name: 'Eclectic', emoji: '🔮', description: 'Mix of styles, curated chaos', category: 'themed', promptModifier: 'eclectic interior design, mix of styles, curated chaos, bold colors, unique pieces' },
  { id: 'maximalist', name: 'Maximalist', emoji: '📚', description: 'More is more, bold patterns, layered', category: 'themed', promptModifier: 'maximalist interior design, more is more, bold patterns, layered decor, vibrant colors' },
  { id: 'gothic', name: 'Gothic', emoji: '🦇', description: 'Dark elegance, dramatic, ornate', category: 'themed', promptModifier: 'gothic interior design, dark elegance, dramatic atmosphere, ornate details, deep colors' },
  { id: 'vaporwave', name: 'Vaporwave', emoji: '🌐', description: 'Pink/blue, nostalgic, surreal', category: 'themed', promptModifier: 'vaporwave interior design, pink and blue neon, nostalgic digital aesthetic, surreal elements' },
  { id: 'cottagecore', name: 'Cottagecore', emoji: '🏡', description: 'Rural idyll, floral, handmade', category: 'themed', promptModifier: 'cottagecore interior, rural idyll, floral patterns, handmade elements, cozy warmth' },
  { id: 'halloween', name: 'Halloween', emoji: '🎃', description: 'Spooky seasonal decor', category: 'seasonal', promptModifier: 'halloween themed interior, spooky decor, pumpkins, cobwebs, dark atmosphere' },
  { id: 'christmas', name: 'Christmas', emoji: '🎄', description: 'Festive holiday warmth', category: 'seasonal', promptModifier: 'christmas themed interior, festive holiday decor, warm lights, garlands, cozy atmosphere' },
];

export const MODES = [
  { id: 'interior-design', name: 'Interior Design', description: 'Redesign your space while maintaining structure', icon: '🎨' },
  { id: 'style-transfer', name: 'Style Transfer', description: 'Apply a new style keeping the same furniture', icon: '🖌️' },
  { id: 'virtual-staging', name: 'Virtual Staging', description: 'Fill empty rooms with furniture and decor', icon: '🏠' },
  { id: 'sketch2image', name: 'Sketch to Image', description: 'Turn sketches into photorealistic renders', icon: '✏️' },
  { id: 'outdoor-design', name: 'Outdoor Design', description: 'Redesign gardens, patios, and exteriors', icon: '🌳' },
  { id: 'empty-space', name: 'Empty the Space', description: 'Remove furniture from your room', icon: '🧹' },
];

export const PEOPLE_OPTIONS = [
  { id: 'none', name: 'No people', value: '' },
  { id: 'man', name: 'Man', value: 'a man sitting in the room' },
  { id: 'woman', name: 'Woman', value: 'a woman sitting in the room' },
  { id: 'couple', name: 'Couple', value: 'a couple sitting in the room' },
  { id: 'family', name: 'Family', value: 'a family in the room' },
  { id: 'friends', name: 'Group of friends', value: 'a group of friends in the room' },
];
